language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=8eeb867f8e7a0cbfc8d6a71615c52dcb88f87d4a72bbe00f0f2ebbc02b031de8

stages:
  - test

go:
  - 1.13.x

sudo: required
dist: trusty

before_install:
  - go get -u golang.org/x/lint/golint
  - make deps
  - curl -L https://github.com/commander-cli/commander/releases/download/v0.3.0/commander-linux-amd64 -o ~/bin/commander
  - chmod +x ~/bin/commander

jobs:
  include:
    - name: macOS Unit
      os: osx
      script:
        - make test

    - name: windows Unit
      os: windows
      before_install:
        - choco install make
      script:
        - make test-windows

    - name: Unit tests
      before_script:
        - curl https://s3.amazonaws.com/codeclimate/test-reporter/test-reporter-0.10.1-linux-amd64 --output test-reporter
        - chmod +x test-reporter
        - ./test-reporter before-build
      script:
        - make test-coverage
      after_script:
        - ./test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT
