name: lint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: ~/go/bin/staticcheck -checks all
